
version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD : yes
       MYSQL_DATABASE : app
       MYSQL_USER : app
       MYSQL_PASSWORD : pass
    ports:
     - '3306:3306'

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - '5432:5432'

